name: "Capacitacion React Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env: 
    AZURE_WEBAPP_NAME: React-kabel-capacitacion20201121014408
    AZURE_WEBAPP_PACKAGE_PATH: './published'
    NETCORE_VERSION: 3.1.301


jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --no-build --configuration Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}